name: Endpoints

on:
  workflow_run:
    workflows: ["Docker"]
    branches: ["master"]
    types: ["completed"]

jobs:
  test-endpoints:
    name: Test endpoints
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up docker
        run: >-
          sudo ./install_docker.sh &&
          sudo systemctl start docker &&
          sudo systemctl start containerd

      - name: Set up env
        run: >-
          touch .env &&
          echo "URL=localhost:5000" >> .env &&
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env &&
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env &&
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env &&
          echo "CERTBOT_EMAIL=autumn.chiu.136@gmail.com" > nginx-certbot.env          

      - name: Test site endpoints
        run: >-
          docker-compose up -d &&
          sleep 5 &&
          curl localhost:5000/mlh/login/ -X POST -d "username=JonSmith&password=pw123" &&
          docker-compose logs &&
          ./test_endpoints.sh localhost:5000
